qtbase: fix build with glibc-2.28
Fixes:
qtbase/5.11.1+gitAUTOINC+74305ba470-r0/git/src/corelib/io/qfilesystemengine_unix.cpp:94:
qtbase/5.11.1+gitAUTOINC+74305ba470-r0/recipe-sysroot/usr/include/linux/stat.h:56:8:
error: redefinition of 'struct statx_timestamp'
 struct statx_timestamp {
        ^~~~~~~~~~~~~~~

qtbase/5.11.1+gitAUTOINC+74305ba470-r0/recipe-sysroot/usr/include/bits/statx.h:25:8:
note: previous definition of 'struct statx_timestamp'
 struct statx_timestamp
        ^~~~~~~~~~~~~~~

You might encounter another error:
qtbase/5.11.1+gitAUTOINC+74305ba470-r0/git/src/corelib/io/qfilesystemengine_unix.cpp:109:12:
error: 'int renameat2(int, const char*, int, const char*, unsigned int)'
was declared 'extern' and later 'static' [-fpermissive]
 static int renameat2(int oldfd, const char *oldpath, int newfd, const char *newpath, unsigned flags)
            ^~~~~~~~~

qtbase/5.11.1+gitAUTOINC+74305ba470-r0/recipe-sysroot/usr/include/stdio.h:164:12:
note: previous declaration of 'int renameat2(int, const char*, int, const char*, unsigned int)'
 extern int renameat2 (int __oldfd, const char *__old, int __newfd,
            ^~~~~~~~~

In that case enable renameat2 in your PACKAGECONFIG.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>