qt5-creator: upgrade to 4.5.1
* old 3.5.1 isn't compatible with Qt 5.11
  qt-creator-opensource-src-3.5.1/src/libs/qmleditorwidgets/contextpanewidgetimage.cpp:891:23:
  error: invalid use of incomplete type 'class QStyle'
  |      QIcon icon(style()->standardIcon(QStyle::SP_DockWidgetCloseButton));
  |                        ^~

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>